2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/.config/wandb/settings
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/settings
2022-02-09 19:33:23,016 WARNING MainThread:6336 [wandb_setup.py:_flush():75] Unknown environment variable: WANDB_CONFIG_DIR
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:_log_setup():386] Logging user logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220209_193323-3i3qbcdd/logs/debug.log
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:_log_setup():387] Logging internal logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220209_193323-3i3qbcdd/logs/debug-internal.log
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x15b572940>
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:init():420] calling init triggers
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'Architecture': 'Basic UNet', 'epochs': 2, 'batch_size': 2, 'learning_rate': 0.0001, 'dropout': 0.5}
2022-02-09 19:33:23,016 INFO    MainThread:6336 [wandb_init.py:init():441] re-initializing run, found existing run on stack: bfptmisc
2022-02-09 19:33:23,017 INFO    MainThread:6336 [wandb_run.py:finish():1468] finishing run wwy/Basic UNet (dropout-0.5 & lr-0.0001 & epochs-2)/bfptmisc
2022-02-09 19:33:23,018 INFO    MainThread:6336 [jupyter.py:save_history():429] not saving jupyter history
2022-02-09 19:33:23,018 INFO    MainThread:6336 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-09 19:33:23,018 INFO    MainThread:6336 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-09 19:33:23,018 INFO    MainThread:6336 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-09 19:33:23,019 INFO    MainThread:6336 [wandb_run.py:_restore():1769] restore
2022-02-09 19:33:23,816 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 638
}

2022-02-09 19:33:24,341 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 638
}

2022-02-09 19:33:24,893 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 4236
}

2022-02-09 19:33:25,000 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,107 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,213 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,319 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,425 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,546 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,648 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,754 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,857 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:25,963 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 638
  total_bytes: 9307
}

2022-02-09 19:33:26,070 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:26,180 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:26,289 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:26,400 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:26,509 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:27,222 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}

2022-02-09 19:33:28,057 INFO    MainThread:6336 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9307
  total_bytes: 9307
}
local_info {
}

2022-02-09 19:33:29,194 INFO    MainThread:6336 [wandb_run.py:_append_history():2144] rendering history
2022-02-09 19:33:29,194 INFO    MainThread:6336 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-09 19:33:29,194 INFO    MainThread:6336 [wandb_run.py:_append_files():2194] logging synced files
2022-02-09 19:33:29,197 INFO    MainThread:6336 [wandb_init.py:init():471] starting backend
2022-02-09 19:33:29,197 INFO    MainThread:6336 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-09 19:33:29,198 INFO    MainThread:6336 [backend.py:ensure_launched():219] starting backend process...
2022-02-09 19:33:29,203 INFO    MainThread:6336 [backend.py:ensure_launched():224] started backend process with pid: 6881
2022-02-09 19:33:29,204 INFO    MainThread:6336 [wandb_init.py:init():480] backend started and connected
2022-02-09 19:33:29,214 INFO    MainThread:6336 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-09 19:33:29,214 INFO    MainThread:6336 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-09 19:33:29,214 INFO    MainThread:6336 [wandb_init.py:init():550] updated telemetry
2022-02-09 19:33:29,216 INFO    MainThread:6336 [wandb_init.py:init():581] communicating current version
2022-02-09 19:33:30,110 INFO    MainThread:6336 [wandb_init.py:init():586] got version response 
2022-02-09 19:33:30,110 INFO    MainThread:6336 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-09 19:33:30,536 INFO    MainThread:6336 [wandb_init.py:init():624] starting run threads in backend
2022-02-09 19:33:31,659 INFO    MainThread:6336 [wandb_run.py:_console_start():1827] atexit reg
2022-02-09 19:33:31,660 INFO    MainThread:6336 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-09 19:33:31,660 INFO    MainThread:6336 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-09 19:33:31,660 INFO    MainThread:6336 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-09 19:33:31,660 INFO    MainThread:6336 [wandb_init.py:init():651] run started, returning control to user process
2022-02-09 19:33:31,673 INFO    MainThread:6336 [wandb_watch.py:watch():43] Watching
2022-02-09 19:33:36,003 INFO    MainThread:6336 [wandb_run.py:finish():1468] finishing run wwy/Basic UNet (dropout-0.5 & lr-0.0001 & epochs-2)/3i3qbcdd
2022-02-09 19:33:36,004 INFO    MainThread:6336 [jupyter.py:save_history():429] not saving jupyter history
2022-02-09 19:33:36,004 INFO    MainThread:6336 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-09 19:33:36,004 INFO    MainThread:6336 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-09 19:33:43,320 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/.config/wandb/settings
2022-02-09 19:33:43,320 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/settings
2022-02-09 19:33:43,320 WARNING MainThread:6336 [wandb_setup.py:_flush():75] Unknown environment variable: WANDB_CONFIG_DIR
2022-02-09 19:33:43,320 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-09 19:33:43,320 INFO    MainThread:6336 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-09 19:33:43,320 INFO    MainThread:6336 [wandb_init.py:_log_setup():386] Logging user logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220209_193343-3bm0ae4z/logs/debug.log
2022-02-09 19:33:43,321 INFO    MainThread:6336 [wandb_init.py:_log_setup():387] Logging internal logs to /Users/wangyangwu/Documents/Maastro/NeuralNets/BasicUNet/wandb/run-20220209_193343-3bm0ae4z/logs/debug-internal.log
2022-02-09 19:33:43,321 INFO    MainThread:6336 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x15cdf8ca0>
2022-02-09 19:33:43,321 INFO    MainThread:6336 [wandb_init.py:init():420] calling init triggers
2022-02-09 19:33:43,321 INFO    MainThread:6336 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'Architecture': 'Basic UNet', 'epochs': 2, 'batch_size': 2, 'learning_rate': 0.0001, 'dropout': 0.5}
2022-02-09 19:33:43,321 INFO    MainThread:6336 [wandb_init.py:init():441] re-initializing run, found existing run on stack: 3i3qbcdd
2022-02-09 19:33:43,323 INFO    MainThread:6336 [wandb_run.py:finish():1468] finishing run wwy/Basic UNet (dropout-0.5 & lr-0.0001 & epochs-2)/3i3qbcdd
2022-02-09 19:33:43,324 INFO    MainThread:6336 [jupyter.py:save_history():429] not saving jupyter history
2022-02-09 19:33:43,325 INFO    MainThread:6336 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-09 19:33:43,325 INFO    MainThread:6336 [wandb_init.py:_jupyter_teardown():318] cleaning up jupyter logic
2022-02-09 19:33:43,325 INFO    MainThread:6336 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-09 19:33:43,325 INFO    MainThread:6336 [wandb_run.py:_restore():1769] restore
2022-02-09 19:33:44,272 INFO    MainThread:6336 [wandb_run.py:_restore():1769] restore
2022-02-09 19:33:44,319 ERROR   MainThread:6336 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1980, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 450, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1474, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1814, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/wangyangwu/miniforge3/envs/maastro/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
